sudo: required

language: bash

services:
  - docker

before_install:
   - docker build -t sergiojuliogu/mads-todolist-2017:0.2 .

script:
   - docker run --rm sergiojuliogu/mads-todolist-2017:0.2 /bin/bash -c "sbt test"
